//--------------------------------
// © Ada Maynek 2024
//--------------------------------
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ada's Works",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="h-full">
      <body className={"h-full bg-gray-200 " + inter.className} >
        {children}
      </body>
    </html>
  );
}
